name: Monthly Auto Commit

on:
  schedule:
    # Runs on the first day of every month at midnight UTC
    - cron: '0 0 1 * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # 这里是你希望自动化进行的更改
        echo "Auto commit on $(date)" > auto_commit.txt

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated commit for $(date +'%Y-%m-%d')"

    - name: Check out the master branch
      run: git checkout master
      
    - name: Pull latest changes
      run: |
        git pull --rebase

    - name: Check for unmerged paths
      run: |
        if git ls-files -u | grep "."; then
          echo "Conflict detected, please resolve conflicts before pushing."
          exit 1
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
